// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9btCF5sEp-CQQ0V8Zq_wLsrc6lLCSjjs',
    appId: '1:867847161323:web:93984ec1d70c918a3085ae',
    messagingSenderId: '867847161323',
    projectId: 'red-de-trabajo',
    authDomain: 'red-de-trabajo.firebaseapp.com',
    storageBucket: 'red-de-trabajo.firebasestorage.app',
    measurementId: 'G-6CBZS0PBVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP5tSKg5HjcaYh9qcd6z5aYgAE316Ywio',
    appId: '1:867847161323:android:d7ff295e75dc00b93085ae',
    messagingSenderId: '867847161323',
    projectId: 'red-de-trabajo',
    storageBucket: 'red-de-trabajo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQCrMQrC8Xzwl26vJHC0rSZEy3J5BY0nc',
    appId: '1:867847161323:ios:1fffd0294b0d49283085ae',
    messagingSenderId: '867847161323',
    projectId: 'red-de-trabajo',
    storageBucket: 'red-de-trabajo.firebasestorage.app',
    iosBundleId: 'com.example.redDeTrabajo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQCrMQrC8Xzwl26vJHC0rSZEy3J5BY0nc',
    appId: '1:867847161323:ios:1fffd0294b0d49283085ae',
    messagingSenderId: '867847161323',
    projectId: 'red-de-trabajo',
    storageBucket: 'red-de-trabajo.firebasestorage.app',
    iosBundleId: 'com.example.redDeTrabajo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9btCF5sEp-CQQ0V8Zq_wLsrc6lLCSjjs',
    appId: '1:867847161323:web:f769e19314da74203085ae',
    messagingSenderId: '867847161323',
    projectId: 'red-de-trabajo',
    authDomain: 'red-de-trabajo.firebaseapp.com',
    storageBucket: 'red-de-trabajo.firebasestorage.app',
    measurementId: 'G-Q26WKW504N',
  );
}
